---
ID: "2d95f20f-9c06-4e65-bfc8-cea679e47a1b"
Parent: "f16c66be-b485-44a9-8211-d96fc75c6c17"
Template: "f16c66be-b485-44a9-8211-d96fc75c6c17"
Path: /sitecore/templates/Feature/PageContent/Rendering Parameters/Page content parameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190525T225026Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
