---
ID: "986edf97-201e-407a-88bf-a51097b1271e"
Parent: "92f4a528-16a6-4fea-b893-dbde7d99a008"
Template: "92f4a528-16a6-4fea-b893-dbde7d99a008"
Path: /sitecore/templates/Project/Website/Components/Footer/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190525T224145Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
